export const products = [
  { slug: "real-estate-deal-analyzer", name: "Real Estate Deal Analyzer", category: "Investment intelligence", status: "In development", summary: "Understand the deal before you make the move.", description: "An AI-powered workspace for real estate investors to structure assumptions, analyze a potential acquisition, and see the details that shape a decision.", audience: "Real estate investors", capabilities: ["Deal and property analysis", "Investment assumption review", "Clear decision-ready summaries"], color: "mint" },
  { slug: "ai-space-revamp", name: "AI Space Revamp", category: "Property visualization", status: "Coming soon", summary: "See what a space could become.", description: "Explore redesign directions for a property with AI-assisted visual concepts that help owners and investors imagine what is possible.", audience: "Owners, investors, and property professionals", capabilities: ["AI-assisted redesign concepts", "Property image exploration", "Visual direction for renovation planning"], color: "sand" },
  { slug: "ai-fix-flip-coach", name: "AI Fix & Flip Coach", category: "Real estate AI", status: "Research phase", summary: "A smarter partner for the next renovation project.", description: "An AI-assisted toolkit in research for scoping renovation work, organizing project assumptions, and pressure-testing a fix-and-flip opportunity.", audience: "Fix-and-flip investors", capabilities: ["Renovation scope planning", "Project assumption review", "Investment scenario exploration"], color: "blue" },
  { slug: "skill-mastery-ai", name: "Skill Mastery AI", category: "Learning systems", status: "Experimental", summary: "Build skills through focused practice.", description: "An experimental learning product exploring personalized practice, progress paths, and ways to make skill development part of the daily routine.", audience: "Independent learners and teams", capabilities: ["Personalized practice paths", "Progress reflection", "Adaptive learning prompts"], color: "lilac" },
  { slug: "ai-digital-twin", name: "AI Digital Twin", category: "Company experiment", status: "Experimental", summary: "A living interface to how Think Zone thinks and builds.", description: "An internal experiment exploring how a useful AI representation of a company can make its methods, ideas, and working knowledge easier to explore.", audience: "Think Zone R&D", capabilities: ["Knowledge exploration", "Method and process discovery", "AI interaction experiments"], color: "mint" },
];

export const solutions = [
  { slug: "ai-strategy", name: "AI Strategy", summary: "Find where AI can make a material difference.", description: "Map real business needs to practical AI opportunities. We help prioritize the work, define a responsible path forward, and move from strategy to a buildable plan.", outcomes: ["Opportunity discovery and prioritization", "Use-case and feasibility assessment", "Roadmap, architecture direction, and next steps"] },
  { slug: "ai-automation", name: "AI Automation", summary: "Give repetitive work a better way to move.", description: "Connect the tools and processes your team already uses with well-scoped automation that reduces manual effort and makes handoffs more dependable.", outcomes: ["Workflow mapping and automation design", "System integration and orchestration", "Human review and exception handling"] },
  { slug: "ai-agents", name: "AI Agents", summary: "Build assistants that can act with purpose.", description: "Develop AI agents that use business context and tools to complete bounded tasks, with the controls and oversight needed for real operations.", outcomes: ["Agent workflows and tool use", "Knowledge retrieval and context design", "Evaluation, guardrails, and observability"] },
  { slug: "ai-product-development", name: "AI Product Development", summary: "Turn an AI idea into software people can use.", description: "Shape and build intelligent applications from product definition through engineering, deployment, and iterative improvement.", outcomes: ["Product definition and experience design", "Full-stack AI engineering", "Deployment and product iteration"] },
  { slug: "data-ai-engineering", name: "Data & AI Engineering", summary: "Build the foundations that make intelligence useful.", description: "Make business data accessible, reliable, and ready to support useful AI experiences through thoughtful pipelines, integrations, and cloud architecture.", outcomes: ["Data integration and pipelines", "Retrieval and application architecture", "Cloud infrastructure and reliability"] },
  { slug: "ai-mvp-development", name: "AI MVP Development", summary: "Learn quickly by putting a focused product in motion.", description: "Reduce uncertainty with a focused, production-minded prototype. Validate the experience and value before committing to a larger build.", outcomes: ["MVP scope and validation plan", "Rapid prototyping and implementation", "Learning review and path to production"] },
];
