import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { PageShell } from "@/components/site-shell";
import { solutions } from "@/lib/content";

export function generateStaticParams() { return solutions.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const solution = solutions.find((entry) => entry.slug === slug); return solution ? { title: solution.name, description: solution.summary, alternates: { canonical: `/solutions/${solution.slug}` } } : {}; }
export default async function SolutionPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const solution = solutions.find((entry) => entry.slug === slug); if (!solution) notFound(); return <PageShell><main className="detail-page"><div className="breadcrumb"><Link href="/solutions">Solutions</Link><span>/</span>{solution.name}</div><section className="detail-hero"><div className="detail-copy"><div className="section-kicker"><span>THINK ZONE / CAPABILITY</span></div><h1>{solution.name.split(" ").slice(0, -1).join(" ")}<br /><span>{solution.name.split(" ").slice(-1)}</span></h1><p className="detail-lede">{solution.description}</p><Link className="button button-dark" href={`/contact?solution=${solution.slug}`}>Talk about your opportunity <span className="arrow">↗</span></Link></div><div className="detail-art mint"><span className="detail-art-index">DISCOVER / DESIGN / BUILD</span><span className="detail-art-core">tz</span><span className="detail-art-foot">THINK ZONE / CAPABILITY</span></div></section><section className="detail-content"><div><div className="section-kicker"><span>WHAT WE DO</span></div><h2>{solution.summary}</h2><p>We bring product thinking and hands-on engineering together, so the work is grounded in your goals and designed to operate in the real world.</p></div><div className="detail-side"><div className="section-kicker"><span>WAYS WE CAN HELP</span></div>{solution.outcomes.map((item, i) => <div className="capability" key={item}><span>0{i + 1}</span>{item}</div>)}</div></section><section className="detail-next"><div><span>READY WHEN YOU ARE</span><h2>Let&apos;s find the<br />right first step.</h2></div><Link className="button button-dark" href="/contact">Start a conversation <span className="arrow">↗</span></Link></section></main></PageShell>; }
